### PR TITLE
Update target python versions

### PR DESCRIPTION
**Pull request by 23pointsNorth**
As per https://devguide.python.org/versions/ Python version 3.5 and 3.6 are EOL. It would make sense to continue testing on 3.6 -> 3.11

### CODE REVIEW

**Comment by SimonBlanke** [comment]
Hello @23pointsNorth,

good idea! I ran all tests for 3.10 and 3.11 yesterday and I found the following problems:

- 3.10 is interpreted as 3.1 in the test matrix. You can read more about it [in this article](https://dev.to/hugovk/the-python-3-1-problem-85g). The solution is to put double quotes around each version number to change the type to string.
- 3.11 has breaking changes for the `random`-module. You can read more about it in [this issue](https://github.com/holoviz/param/issues/602). I got the [same error](https://github.com/SimonBlanke/Gradient-Free-Optimizers/actions/runs/3412891108/jobs/5678966853) when testing the optimization-backend in 3.11. So we have to do without 3.11 support for the time being. If you like you can open an issue for v3.11 support (you can skip the issue template for that one).
- I would like to keep testing in version 3.5 for now (unless there is a strong argument against it). 3.5 has unordered dictionaries, which might return in future versions of python. Making Hyperactive work with unordered dictionaries was [pretty difficult](https://github.com/SimonBlanke/Hyperactive/issues/15). So I would like to keep this on my radar for now.

I didn't expect this to blow up like this, but I am grateful, because I learned a lot reading about these problems :-)

Let me know what you think about these problems.

**Review by SimonBlanke — CHANGES_REQUESTED** [review]
https://github.com/SimonBlanke/Hyperactive/pull/58#issuecomment-1307609008

**Comment by 23pointsNorth** [comment]
Hi @SimonBlanke ,
Thanks for the good links above. With the GFO fix, I've updated the testing matrix to include a string version representation like the GFO repo.

As far as I know, as an open source project it makes no difference per se (i.e. not sure when would make sense to sunset versions)?  
Let's see what the CI says and feel free to edit/change things as required.

**Review by SimonBlanke — APPROVED** [review]

**Comment by SimonBlanke** [comment]
Hello @23pointsNorth,

thanks for the contribution! :-)
I was a bit reluctant to merge, because of the error: [Version 3.5 with arch x64 not found](https://github.com/23pointsNorth/Gradient-Free-Optimizers/actions/runs/3427292210/jobs/5710490180). But it did not occur on my end. 
Maybe 3.5 is interpreted as 3.5.0 (which is not supported), but that is just speculation. If it occurs again I will try to write the version as "3.5.x".

> Are there any timing tests?

Currently not, but I do not expect any significant speed-ups on our end. Usually the biggest part of the computation time is spend on the model inside the objective-function (the smbo might be an exception). But it would be interesting to see how it affects Hyperactive.

**Comment by 23pointsNorth** [comment]
Looking at the CI everything looks green, so hopefully, it wasn't too much of a hassle. 

Thanks for the great library!

**Pull request merged**
