### PR TITLE
Removed pandas < 2 requirement as all tests pass with pandas 2

### PR DESCRIPTION
**Pull request by joshua-gould**

### CODE REVIEW

**Comment by SimonBlanke** [comment]
I installed pandas 2 locally and ran all tests. The first test to fail was "test_issue_25.py":
"AttributeError: 'DataFrame' object has no attribute 'append'"

How did you run the tests, that gave you a positive result?

**Comment by joshua-gould** [comment]
The tests ran using the existing github action

**Comment by SimonBlanke** [comment]
I just saw your request in the actions for a test run. The tests are running now.

**Comment by joshua-gould** [comment]
Thanks. Good catch.

**Pull request closed without merging**
